### ISSUE TITLE
Google shopping tab doesn't display anything

### ISSUE THREAD

**Issue by funkjaw666** [EECSB/Google-Search-Customizer#34]
With "remove ad settings" radio selected, the shopping tab on google doesn't display anything at all. Unsure if intended by design or bug?

**Comment by EECSB** [comment]
No, this was a bug. 
It's fixed now but it might take a few days for the update to be pushed out by the Chrome web store/Firefox add-ons.

**Comment by valantur** [comment]
This is still a problem for me. Results show up for a brief moment and then disappear. Great extension otherwise!

<img width="1084" alt="Image" src="https://github.com/user-attachments/assets/37cfe8e3-4bd6-47d3-bc12-d6a24aafa13a" />

**Comment by EECSB** [comment]
[Fixed](https://github.com/EECSB/Google-Search-Customizer/commit/b2458b43f933bbbcc983536f9b14a2782df382ee), it might take a few days for the update(version 1.2.15) to be pushed out by the Chrome web store/Firefox add-ons.
